plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	// CurseMaven for TerraBlender and GeckoLib
	maven {
		name = "CurseMaven"
		url = "https://www.cursemaven.com"
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	// TerraBlender Dependency (via CurseMaven file ID)
	implementation "curse.maven:terrablender-fabric-565956:7933873"
	// GeckoLib Dependency (via CurseMaven file ID)
	implementation "curse.maven:geckolib-388172:7913636"
}

processResources {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE

	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${base.archivesName.get()}"}
	}
}

sourcesJar {
	exclude '.cache/**' // Don't include the cache folder
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE // If you find duplicates, just pick one and move on
}

sourceSets {
	main {
		resources {
			srcDirs += [
					'src/main/generated'
			]
		}
	}
}

task executeReflector(type: JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.warpgames.vesperwilds.Reflector'
}